### ISSUE TITLE
Program dosen't say 'You are correct,' even if answer is correct.

### ISSUE THREAD

**Issue by thatoneguy107** [thatoneguy107/FunMath#1]
Discovered by ThatOneGuy107 on 12/6/2015

**Comment by amonger** [comment]
It's because of casting. When you have an input, its a string, but when you calculate the answer its an integer / float.

So if you put 
`
 if float(user_answer) == float(answer):
`
It would work. 😄

**Comment by thatoneguy107** [comment]
Thx! This is an abandoned project though haven't been on github for ages, but thanks for the knowledge!
